/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import hospital.Hospital;
import hospital.HospitalDAO;
import hospital.HospitalTableModel;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import usuario.Usuario;
import usuario.UsuarioDAO;
import usuario.UsuarioTableModel;
import util.FormataTamanhoColunasJTable;
import vitima.Vitima;
import vitima.VitimaDAO;
import vitima.VitimaTableModel;

/**
 *
 * @author Katyeudo
 */
public class ConsultarFichaNotificacaoHospital extends javax.swing.JFrame {

    Hospital hospital = new Hospital();
    HospitalDAO hospitalDAO = new HospitalDAO();
    Usuario usuario = new Usuario();

    public ConsultarFichaNotificacaoHospital(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        atualizarTabela();
    }

    public void atualizarTabela() {

        JTableHeader cabecalho = tabelaHospital.getTableHeader();
        cabecalho.setFont(new Font("Tahoma", Font.BOLD, 15));

        HospitalTableModel htm = new HospitalTableModel(hospitalDAO.listarHospital());
        tabelaHospital.setModel(htm);
        tabelaHospital.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        FormataTamanhoColunasJTable.packColumns(tabelaHospital, 1);
        ((DefaultTableCellRenderer) tabelaHospital.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHospital = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Dados Hospitalares");
        setMinimumSize(new java.awt.Dimension(695, 500));
        setPreferredSize(new java.awt.Dimension(695, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        tabelaHospital.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tabelaHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaHospitalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaHospital);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 50, 530, 180);

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-new-icon-22-2.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(140, 370, 100, 80);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-2.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setMaximumSize(new java.awt.Dimension(79, 79));
        btnExcluir.setMinimumSize(new java.awt.Dimension(79, 79));
        btnExcluir.setPreferredSize(new java.awt.Dimension(79, 79));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(260, 370, 100, 80);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(380, 370, 100, 80);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Voltar.png"))); // NOI18N
        btnVoltar.setText("Principal");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 370, 100, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rodape-4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 400, 700, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomarca_ligue180_2015(1)-2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 240, 210, 130);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 39, 89));
        jLabel15.setText("Consulta de Dados Hospitalares");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 10, 270, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tabelaHospital.getSelectedRow();
        Object[] options = {"Sim", "Não"};
        if (linha == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        } else if (JOptionPane.showOptionDialog(null, "Deseja mesmo excluir esse Cadastro?", "Excluir Cadastro",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION) {
            hospital = hospitalDAO.pesquisarHospitalPorID((int) tabelaHospital.getValueAt(linha, 0));
            hospitalDAO.deletar(hospital);
            JOptionPane.showMessageDialog(null, "Cadastro excluído com sucesso");
            atualizarTabela();
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tabelaHospital.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        } else {
            hospital = hospitalDAO.pesquisarHospitalPorID((int) tabelaHospital.getValueAt(linha, 0));
            FichaNotificacaoHospital fichaNotificacaoHospital = new FichaNotificacaoHospital(this.usuario);
            fichaNotificacaoHospital.setVisible(true);
            fichaNotificacaoHospital.hospital = hospital;
            fichaNotificacaoHospital.atualizarConsulta();
            fichaNotificacaoHospital.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal(this.usuario);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] options = {"Sim", "Não"};
        if (JOptionPane.showOptionDialog(null, "Deseja mesmo sair da aplicação?", "Consulta Hospitlar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void tabelaHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaHospitalMouseClicked
        if (evt.getClickCount() == 2) {
            btnEditarActionPerformed(null);
        }
    }//GEN-LAST:event_tabelaHospitalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFichaNotificacaoHospital(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHospital;
    // End of variables declaration//GEN-END:variables
}
