/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import delegacia.Delegacia;
import delegacia.DelegaciaDAO;
import hospital.Hospital;
import hospital.HospitalDAO;
import javax.swing.JOptionPane;
import usuario.Usuario;

/**
 *
 * @author Katyeudo
 */
public class FichaNotificacaoDelegacia extends javax.swing.JFrame {

    Delegacia delegacia;
    DelegaciaDAO delegaciaDAO;

    Usuario usuario = new Usuario();
    public FichaNotificacaoDelegacia(Usuario usuario) {
         this.usuario = usuario;

        delegacia = new Delegacia();
        delegaciaDAO = new DelegaciaDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jcNumeroEnvolvidos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jcSexo = new javax.swing.JComboBox<>();
        labelPonto1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jcRelacao = new javax.swing.JComboBox<>();
        labelPonto4 = new javax.swing.JLabel();
        jPanel91 = new javax.swing.JPanel();
        jcAlcool = new javax.swing.JComboBox<>();
        labelPonto3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jcSeOcorreuViolencia = new javax.swing.JComboBox<>();
        labelPonto2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jcSeOcorreuPenetracao = new javax.swing.JComboBox<>();
        labelPonto5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha de Notificação de Delegacia");
        setMinimumSize(new java.awt.Dimension(879, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Voltar.png"))); // NOI18N
        btnVoltar.setText("Principal");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(30, 320, 104, 80);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-icon-31-2.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(150, 320, 104, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("* Dados Obrigatórios");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 320, 130, 15);

        Pesquisar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-search-128-2.png"))); // NOI18N
        Pesquisar.setText("Pesquisar");
        Pesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisar);
        Pesquisar.setBounds(617, 320, 120, 80);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(750, 320, 110, 80);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de Envolvidos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jcNumeroEnvolvidos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcNumeroEnvolvidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Um", "Dois ou mais", "Ignorado" }));
        jcNumeroEnvolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNumeroEnvolvidosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcNumeroEnvolvidos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcNumeroEnvolvidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(670, 40, 190, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rodape-3.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 350, 880, 80);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo do provável autor da agressão", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setMinimumSize(new java.awt.Dimension(845, 70));

        jcSexo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Masculino", "Feminino", "Ambos os Sexo", "Ignorado" }));
        jcSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSexoActionPerformed(evt);
            }
        });

        labelPonto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto1.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto1.setText("*");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(573, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(390, 120, 270, 70);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relação com a Pessoa Atendida", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jcRelacao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcRelacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Pai", "Mãe", "Padrasto", "Madrasta", "Cônjuge", "Ex-Cônjuge", "Namorado(a)", "Amigos/conhecidos", "Desconhecido", "Cuidador", "Patrão/chefe", "Pessoa com Relação Institucional", "Ignorado" }));

        labelPonto4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto4.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto4.setText("*");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto4)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(20, 120, 360, 70);

        jPanel91.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supeita de uso de álcool", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jcAlcool.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcAlcool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Sim", "Não", "Ignorado" }));
        jcAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAlcoolActionPerformed(evt);
            }
        });

        labelPonto3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto3.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto3.setText("*");

        javax.swing.GroupLayout jPanel91Layout = new javax.swing.GroupLayout(jPanel91);
        jPanel91.setLayout(jPanel91Layout);
        jPanel91Layout.setHorizontalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto3)
                .addContainerGap())
        );
        jPanel91Layout.setVerticalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel91Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPonto3)
                    .addComponent(jcAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel91);
        jPanel91.setBounds(670, 120, 190, 68);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 39, 89));
        jLabel15.setText("Ficha de Notificação de Delegacia");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 10, 280, 20);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Se ocorreu violência sexual, qual o tipo?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel8.setMinimumSize(new java.awt.Dimension(845, 70));

        jcSeOcorreuViolencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcSeOcorreuViolencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Assédio Sexual", "Estupro", "Atentado Violento ao Pudor", "Pornografia Infantil", "Exploração Sexual", "Não", "Ignorado" }));
        jcSeOcorreuViolencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSeOcorreuViolenciaActionPerformed(evt);
            }
        });

        labelPonto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto2.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto2.setText("*");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcSeOcorreuViolencia, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto2)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcSeOcorreuViolencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(20, 40, 360, 70);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Se ocorreu penetração, qual o tipo?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel9.setMinimumSize(new java.awt.Dimension(845, 70));

        jcSeOcorreuPenetracao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcSeOcorreuPenetracao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Oral", "Anal", "Vaginal", "Não", "Ignorado" }));
        jcSeOcorreuPenetracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSeOcorreuPenetracaoActionPerformed(evt);
            }
        });

        labelPonto5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto5.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto5.setText("*");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcSeOcorreuPenetracao, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(573, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcSeOcorreuPenetracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(390, 40, 270, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaPrincipal(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (preencherDados()) {

            preencherDados();

            if (delegacia.getIdDelegacia() != 0) {
                delegaciaDAO.atualizar(delegacia);
                JOptionPane.showMessageDialog(null, "Ficha atualizada com sucesso!");
            } else {
                delegaciaDAO.salvar(delegacia);

                JOptionPane.showMessageDialog(null, "Ficha cadastrada com sucesso!");
            }

            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Campo obrigatório não preenchido!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    private void limparCampos() {

        jcSexo.setSelectedIndex(0);
        jcRelacao.setSelectedIndex(0);
        jcNumeroEnvolvidos.setSelectedItem("---");
        jcAlcool.setSelectedIndex(0);
        jcSeOcorreuPenetracao.setSelectedIndex(0);
        jcSeOcorreuViolencia.setSelectedIndex(0);

        delegacia = new Delegacia();
    }

    private boolean preencherDados() {

        if (!((jcNumeroEnvolvidos.getSelectedItem().equals("---")) || (jcSexo.getSelectedItem().equals("---"))
                || (jcRelacao.getSelectedItem().equals("---")) || (jcSeOcorreuPenetracao.getSelectedItem().equals("---"))
                || (jcSeOcorreuViolencia.getSelectedItem().equals("---")) || (jcAlcool.getSelectedItem().equals("---")))) {

            delegacia.setViolenciaSexoAutor(jcSexo.getSelectedItem().toString());
            delegacia.setViolenciaRelacaoPessoaAtendida(jcRelacao.getSelectedItem().toString());
            delegacia.setViolenciaSeOcorreuPenetracao(jcSeOcorreuPenetracao.getSelectedItem().toString());
            delegacia.setViolenciaNumeroEnvolvidos(jcNumeroEnvolvidos.getSelectedItem().toString());
            delegacia.setViolenciaSeOcorreuViolencia(jcSeOcorreuViolencia.getSelectedItem().toString());
            delegacia.setViolenciaSuspeitaAlcool(jcAlcool.getSelectedItem().toString());

            return true;
        }

        return false;
    }

    public void atualizarConsulta() {

        jcSexo.setSelectedItem(delegacia.getViolenciaSexoAutor());
        jcRelacao.setSelectedItem(delegacia.getViolenciaRelacaoPessoaAtendida());
        jcNumeroEnvolvidos.setSelectedItem(delegacia.getViolenciaNumeroEnvolvidos());
        jcSeOcorreuViolencia.setSelectedItem(delegacia.getViolenciaSeOcorreuViolencia());
        jcSeOcorreuPenetracao.setSelectedItem(delegacia.getViolenciaSeOcorreuPenetracao());
        jcAlcool.setSelectedItem(delegacia.getViolenciaSuspeitaAlcool());

    }
    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        ConsultarFichaNotificacaoDelegacia consultarFichaNotificacaoDelegacia = new ConsultarFichaNotificacaoDelegacia(this.usuario);
        consultarFichaNotificacaoDelegacia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] options = {"Sim", "Não"};
        if (JOptionPane.showOptionDialog(null, "Deseja mesmo sair da aplicação?", "Ficha de Notificação Delegacia",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void jcSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSexoActionPerformed
        
    }//GEN-LAST:event_jcSexoActionPerformed

    private void jcNumeroEnvolvidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNumeroEnvolvidosActionPerformed
        
    }//GEN-LAST:event_jcNumeroEnvolvidosActionPerformed

    private void jcSeOcorreuViolenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSeOcorreuViolenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcSeOcorreuViolenciaActionPerformed

    private void jcSeOcorreuPenetracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSeOcorreuPenetracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcSeOcorreuPenetracaoActionPerformed

    private void jcAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAlcoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcAlcoolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaNotificacaoDelegacia(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JComboBox<String> jcAlcool;
    private javax.swing.JComboBox<String> jcNumeroEnvolvidos;
    private javax.swing.JComboBox<String> jcRelacao;
    private javax.swing.JComboBox<String> jcSeOcorreuPenetracao;
    private javax.swing.JComboBox<String> jcSeOcorreuViolencia;
    private javax.swing.JComboBox<String> jcSexo;
    private javax.swing.JLabel labelPonto1;
    private javax.swing.JLabel labelPonto2;
    private javax.swing.JLabel labelPonto3;
    private javax.swing.JLabel labelPonto4;
    private javax.swing.JLabel labelPonto5;
    // End of variables declaration//GEN-END:variables
}
