/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import hospital.Hospital;
import hospital.HospitalDAO;
import javax.swing.JOptionPane;
import usuario.Usuario;

/**
 *
 * @author Katyeudo
 */
public class FichaNotificacaoHospital extends javax.swing.JFrame {

    Hospital hospital;
    HospitalDAO hospitalDAO;

    Usuario usuario = new Usuario();
    public FichaNotificacaoHospital(Usuario usuario) {
         this.usuario = usuario;

        hospital = new Hospital();
        hospitalDAO = new HospitalDAO();
        initComponents();
        labelPonto3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jcEvolucaoCaso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtOutros = new javax.swing.JTextField();
        jcConsequencias = new javax.swing.JComboBox<>();
        labelPonto1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jcProcedimento = new javax.swing.JComboBox<>();
        labelPonto4 = new javax.swing.JLabel();
        jPanel91 = new javax.swing.JPanel();
        txtDataObitoAgressao = new javax.swing.JFormattedTextField();
        labelPonto3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha de Notificação Hospitalar");
        setMinimumSize(new java.awt.Dimension(892, 420));
        setPreferredSize(new java.awt.Dimension(892, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Voltar.png"))); // NOI18N
        btnVoltar.setText("Principal");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(30, 290, 104, 80);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-icon-31-2.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(150, 290, 104, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("* Dados Obrigatórios");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 290, 130, 15);

        Pesquisar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-search-128-2.png"))); // NOI18N
        Pesquisar.setText("Pesquisar");
        Pesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisar);
        Pesquisar.setBounds(617, 290, 120, 80);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(750, 290, 110, 80);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evolução do Caso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jcEvolucaoCaso.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcEvolucaoCaso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Alta", "Encaminhamento ambulatorial", "Encaminhamento hospitalar", "Evasão/Fuga", "Óbito pela agressão", "Óbito por outras causas", "Ignorado" }));
        jcEvolucaoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEvolucaoCasoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcEvolucaoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcEvolucaoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(340, 120, 296, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rodape-3.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 310, 880, 80);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consequências da ocorrência detectadas no momento da notificação", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setMinimumSize(new java.awt.Dimension(845, 70));

        txtOutros.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtOutros.setEnabled(false);

        jcConsequencias.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcConsequencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Aborto", "Gravidez", "DST", "Tentativa de Suicídio", "Ignorado", "Outros" }));
        jcConsequencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcConsequenciasActionPerformed(evt);
            }
        });

        labelPonto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto1.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto1.setText("*");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcConsequencias, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcConsequencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 40, 840, 70);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procedimento indicado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jcProcedimento.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcProcedimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Profilaxia DST", "Profilaxia HIV", "Profilaxia Hepatite B", "Coleta de Sangue", "Coleta de Sêmen", "Coleta de Secreção Vaginal", "Contracepcao de Emergencia", "Comunicação de Acidente de Trabalho", "Aborto Previsto em Lei" }));

        labelPonto4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto4.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto4.setText("*");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto4)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(20, 120, 310, 70);

        jPanel91.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Se Óbito pela Agressão, Data", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        try {
            txtDataObitoAgressao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataObitoAgressao.setEnabled(false);
        txtDataObitoAgressao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDataObitoAgressao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataObitoAgressaoKeyPressed(evt);
            }
        });

        labelPonto3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPonto3.setForeground(new java.awt.Color(204, 0, 0));
        labelPonto3.setText("*");

        javax.swing.GroupLayout jPanel91Layout = new javax.swing.GroupLayout(jPanel91);
        jPanel91.setLayout(jPanel91Layout);
        jPanel91Layout.setHorizontalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addComponent(txtDataObitoAgressao, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPonto3)
                .addGap(16, 16, 16))
        );
        jPanel91Layout.setVerticalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel91Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataObitoAgressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPonto3))
                .addContainerGap())
        );

        getContentPane().add(jPanel91);
        jPanel91.setBounds(640, 120, 220, 68);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 39, 89));
        jLabel15.setText("Ficha de Notificação Hospitalar");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 10, 252, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaPrincipal(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (preencherDados()) {

            preencherDados();

            if (hospital.getIdHospital() != 0) {
                hospitalDAO.atualizar(hospital);
                JOptionPane.showMessageDialog(null, "Ficha atualizada com sucesso!");
            } else {
                hospitalDAO.salvar(hospital);

                JOptionPane.showMessageDialog(null, "Ficha cadastrada com sucesso!");
            }

            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Campo obrigatório não preenchido!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    private void limparCampos() {

        jcConsequencias.setSelectedIndex(0);
        txtOutros.setText("");
        jcProcedimento.setSelectedIndex(0);

        jcEvolucaoCaso.setSelectedItem("---");
        txtDataObitoAgressao.setText("");
        txtDataObitoAgressao.setEnabled(false);
        txtOutros.setEnabled(false);

        hospital = new Hospital();
        //this.dispose();
    }

    private boolean preencherDados() {

        if (!((jcEvolucaoCaso.getSelectedItem().equals("---")) || (jcConsequencias.getSelectedItem().equals("---"))
                || (jcProcedimento.getSelectedItem().equals("---")))) {

            hospital.setConsequencias(jcConsequencias.getSelectedItem().toString());
            hospital.setHospitalOutroQual(txtOutros.getText());
            hospital.setProcedimento(jcProcedimento.getSelectedItem().toString());

            hospital.setHospitalEvolucao(jcEvolucaoCaso.getSelectedItem().toString());

            return true;
        }

        return false;
    }

    public void atualizarConsulta() {

        jcConsequencias.setSelectedItem(hospital.getConsequencias());
        jcProcedimento.setSelectedItem(hospital.getProcedimento());

        txtOutros.setText(hospital.getHospitalOutroQual());
        txtDataObitoAgressao.setText(hospital.getHospitalSeObitoData());

        jcEvolucaoCaso.setSelectedItem(hospital.getHospitalEvolucao());
        
        
        

    }
    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        ConsultarFichaNotificacaoHospital consultarFichaNotificacaoHospital = new ConsultarFichaNotificacaoHospital(this.usuario);
        consultarFichaNotificacaoHospital.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] options = {"Sim", "Não"};
        if (JOptionPane.showOptionDialog(null, "Deseja mesmo sair da aplicação?", "Ficha de Notificação Hospitalar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void jcConsequenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcConsequenciasActionPerformed
        if (jcConsequencias.getSelectedItem().equals("Outros")) {
            txtOutros.setEnabled(true);
            hospital.setHospitalOutroQual(txtOutros.getText());
        } else {
            txtOutros.setEnabled(false);
        }
    }//GEN-LAST:event_jcConsequenciasActionPerformed

    private void jcEvolucaoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEvolucaoCasoActionPerformed
        if (jcEvolucaoCaso.getSelectedItem().equals("Óbito pela agressão")) {
            labelPonto3.setVisible(true);
            txtDataObitoAgressao.setEnabled(true);
            hospital.setHospitalSeObitoData(txtDataObitoAgressao.getText());
        } else {
            txtDataObitoAgressao.setEnabled(false);
        }
    }//GEN-LAST:event_jcEvolucaoCasoActionPerformed

    private void txtDataObitoAgressaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataObitoAgressaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataObitoAgressaoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaNotificacaoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaNotificacaoHospital(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JComboBox<String> jcConsequencias;
    private javax.swing.JComboBox<String> jcEvolucaoCaso;
    private javax.swing.JComboBox<String> jcProcedimento;
    private javax.swing.JLabel labelPonto1;
    private javax.swing.JLabel labelPonto3;
    private javax.swing.JLabel labelPonto4;
    private javax.swing.JFormattedTextField txtDataObitoAgressao;
    private javax.swing.JTextField txtOutros;
    // End of variables declaration//GEN-END:variables
}
