/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import usuario.Usuario;

/**
 *
 * @author Katyeudo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario usuario = new Usuario();

    public TelaPrincipal(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        labelTipoUsuario.setText(usuario.getFuncao());
        if (usuario.getFuncao().equalsIgnoreCase("CREAS")) {
            cadastrarHospital.setEnabled(false);
            cadastrarUsuarios.setEnabled(false);
            cadastrarDelegacia.setEnabled(false);
            
            gerenciarHospital.setEnabled(false);
            gerenciarUsuarios.setEnabled(false);
            gerenciarDelegacia.setEnabled(false);
            
        }
        if (usuario.getFuncao().equalsIgnoreCase("Hospital")) {
            cadastrarCreas.setEnabled(false);
            cadastrarUsuarios.setEnabled(false);
            cadastrarDelegacia.setEnabled(false);
            
            gerenciarCreas.setEnabled(false);
            gerenciarUsuarios.setEnabled(false);
            gerenciarDelegacia.setEnabled(false);
 
        }
        
        if (usuario.getFuncao().equalsIgnoreCase("Delegacia")) {
            cadastrarCreas.setEnabled(false);
            cadastrarUsuarios.setEnabled(false);
            cadastrarHospital.setEnabled(false);
            
            gerenciarCreas.setEnabled(false);
            gerenciarUsuarios.setEnabled(false);
            gerenciarHospital.setEnabled(false);
 
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSair1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTipoUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        cadastrarUsuarios = new javax.swing.JMenuItem();
        cadastrarFicha = new javax.swing.JMenuItem();
        cadastrarCreas = new javax.swing.JMenuItem();
        cadastrarHospital = new javax.swing.JMenuItem();
        cadastrarDelegacia = new javax.swing.JMenuItem();
        jmGerenciar = new javax.swing.JMenu();
        gerenciarUsuarios = new javax.swing.JMenuItem();
        gerenciarFicha = new javax.swing.JMenuItem();
        gerenciarCreas = new javax.swing.JMenuItem();
        gerenciarHospital = new javax.swing.JMenuItem();
        gerenciarDelegacia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 221, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 530));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomarca_ligue180_2015(1)-3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 100, 340, 210);

        btnSair1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loggof.png"))); // NOI18N
        btnSair1.setText("LOGOFF");
        btnSair1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair1);
        btnSair1.setBounds(560, 370, 100, 90);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(680, 370, 100, 90);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Disque-Denúncia -  Exploração sexual a crianças e adolescentes. Disque 100");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 440, 540, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 39, 89));
        jLabel3.setText("Usuário:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 410, 80, 20);

        labelTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTipoUsuario.setForeground(new java.awt.Color(36, 39, 89));
        labelTipoUsuario.setText("Tipo");
        jPanel1.add(labelTipoUsuario);
        labelTipoUsuario.setBounds(90, 410, 440, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 520);

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jmCadastrar.setText("Cadastrar");
        jmCadastrar.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N

        cadastrarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cadastrarUsuarios.setText("Usuários");
        cadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuariosActionPerformed(evt);
            }
        });
        jmCadastrar.add(cadastrarUsuarios);

        cadastrarFicha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cadastrarFicha.setText("Ficha de Notificação");
        cadastrarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFichaActionPerformed(evt);
            }
        });
        jmCadastrar.add(cadastrarFicha);

        cadastrarCreas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cadastrarCreas.setText("CREAS");
        cadastrarCreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCreasActionPerformed(evt);
            }
        });
        jmCadastrar.add(cadastrarCreas);

        cadastrarHospital.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cadastrarHospital.setText("Hospital");
        cadastrarHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarHospitalActionPerformed(evt);
            }
        });
        jmCadastrar.add(cadastrarHospital);

        cadastrarDelegacia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cadastrarDelegacia.setText("Delegacia");
        cadastrarDelegacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDelegaciaActionPerformed(evt);
            }
        });
        jmCadastrar.add(cadastrarDelegacia);

        jMenuBar1.add(jmCadastrar);

        jmGerenciar.setText("Gerenciar");
        jmGerenciar.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N

        gerenciarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gerenciarUsuarios.setText("Usuários");
        gerenciarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarUsuariosActionPerformed(evt);
            }
        });
        jmGerenciar.add(gerenciarUsuarios);

        gerenciarFicha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gerenciarFicha.setText("Ficha de Notificação");
        gerenciarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarFichaActionPerformed(evt);
            }
        });
        jmGerenciar.add(gerenciarFicha);

        gerenciarCreas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gerenciarCreas.setText("CREAS");
        gerenciarCreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarCreasActionPerformed(evt);
            }
        });
        jmGerenciar.add(gerenciarCreas);

        gerenciarHospital.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gerenciarHospital.setText("Hospital");
        gerenciarHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarHospitalActionPerformed(evt);
            }
        });
        jmGerenciar.add(gerenciarHospital);

        gerenciarDelegacia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gerenciarDelegacia.setText("Delegacia");
        gerenciarDelegacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarDelegaciaActionPerformed(evt);
            }
        });
        jmGerenciar.add(gerenciarDelegacia);

        jMenuBar1.add(jmGerenciar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] options = {"Sim", "Não"};
        if (JOptionPane.showOptionDialog(null, "Deseja mesmo sair da aplicação?", "Tela Principal",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void cadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuariosActionPerformed
        //Passar por parâmetro um usuário
        new TelaCadastroUsuario(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarUsuariosActionPerformed

    private void cadastrarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFichaActionPerformed
        new FichaNotificacao(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarFichaActionPerformed

    private void cadastrarDelegaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDelegaciaActionPerformed
        new FichaNotificacaoDelegacia(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarDelegaciaActionPerformed

    private void gerenciarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarUsuariosActionPerformed
        new ConsultarCadastro(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarUsuariosActionPerformed

    private void gerenciarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarFichaActionPerformed
        new ConsultarFichaNotificacao(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarFichaActionPerformed

    private void gerenciarDelegaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarDelegaciaActionPerformed
        new ConsultarFichaNotificacaoDelegacia(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarDelegaciaActionPerformed

    private void cadastrarHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarHospitalActionPerformed
        new FichaNotificacaoHospital(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarHospitalActionPerformed

    private void gerenciarHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarHospitalActionPerformed
        new ConsultarFichaNotificacaoHospital(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarHospitalActionPerformed

    private void cadastrarCreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCreasActionPerformed
        new FichaNotificacaoCreas(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarCreasActionPerformed

    private void gerenciarCreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarCreasActionPerformed
        new ConsultarFichaNotificacaoCreas(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerenciarCreasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JMenuItem cadastrarCreas;
    private javax.swing.JMenuItem cadastrarDelegacia;
    private javax.swing.JMenuItem cadastrarFicha;
    private javax.swing.JMenuItem cadastrarHospital;
    private javax.swing.JMenuItem cadastrarUsuarios;
    private javax.swing.JMenuItem gerenciarCreas;
    private javax.swing.JMenuItem gerenciarDelegacia;
    private javax.swing.JMenuItem gerenciarFicha;
    private javax.swing.JMenuItem gerenciarHospital;
    private javax.swing.JMenuItem gerenciarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmGerenciar;
    private javax.swing.JLabel labelTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
