/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import usuario.Usuario;
import usuario.UsuarioDAO;
import util.BarraProgresso;

/**
 *
 * @author Katyeudo
 */
public class TelaLogin extends javax.swing.JFrame implements Serializable{

    Usuario usuario;
    UsuarioDAO usuarioDAO;
    boolean clicou = false;

    public TelaLogin() {
        initComponents();
        usuario = new Usuario();
        usuarioDAO = new UsuarioDAO();
        txtLogin.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDal = new javax.swing.JButton();
        lblNomeSenha = new javax.swing.JLabel();
        lblNomeLogin = new javax.swing.JLabel();
        labelTexto = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        labelIcone = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 221, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 530));
        jPanel1.setLayout(null);

        btnDal.setBackground(new java.awt.Color(67, 45, 119));
        btnDal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho.png"))); // NOI18N
        btnDal.setBorder(null);
        btnDal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDalMouseClicked(evt);
            }
        });
        btnDal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDalActionPerformed(evt);
            }
        });
        jPanel1.add(btnDal);
        btnDal.setBounds(10, 10, 50, 30);

        lblNomeSenha.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        lblNomeSenha.setText("SENHA");
        jPanel1.add(lblNomeSenha);
        lblNomeSenha.setBounds(180, 170, 100, 33);

        lblNomeLogin.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        lblNomeLogin.setText("LOGIN");
        jPanel1.add(lblNomeLogin);
        lblNomeLogin.setBounds(180, 90, 90, 33);

        labelTexto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTexto.setText("Disque-Denúncia -  Exploração sexual a crianças e adolescentes. Disque 100");
        jPanel1.add(labelTexto);
        labelTexto.setBounds(10, 460, 630, 26);

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sairb.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(690, 400, 90, 90);

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtSenha.setBorder(null);
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(310, 170, 190, 30);

        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo5.png"))); // NOI18N
        jPanel1.add(lblSenha);
        lblSenha.setBounds(290, 150, 250, 70);

        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLogin.setBorder(null);
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        jPanel1.add(txtLogin);
        txtLogin.setBounds(310, 90, 190, 30);

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo5.png"))); // NOI18N
        jPanel1.add(lblLogin);
        lblLogin.setBounds(290, 70, 250, 70);

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entrar-2.png"))); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(320, 260, 180, 53);

        labelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomarca_ligue180_2015(1)-2.png"))); // NOI18N
        jPanel1.add(labelIcone);
        labelIcone.setBounds(580, 10, 210, 130);

        labelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        labelLogin.setText("jLabel7");
        jPanel1.add(labelLogin);
        labelLogin.setBounds(0, 0, 800, 520);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoLogin2.png"))); // NOI18N
        jPanel1.add(labelFundo);
        labelFundo.setBounds(4, 0, 790, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        usuario = usuarioDAO.autenticar(txtLogin.getText(), new String(txtSenha.getPassword()));
        if ((usuario == null) || (txtLogin.getText().equals("")) || (txtSenha.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Campos inválidos!");
            limparCampos();
            txtLogin.requestFocus();
        } else {
            BarraProgresso barraProgresso = new BarraProgresso(null, rootPaneCheckingEnabled);
            barraProgresso.setVisible(true);
            new TelaPrincipal(usuario).setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] options = {"Sim", "Não"};
        if (JOptionPane.showOptionDialog(null, "Deseja mesmo sair da aplicação?", "Tela Login",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void btnDalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDalActionPerformed
        if (!clicou) {
            dalto();
            clicou = true;
        } else {
            naoDalto();
            clicou = false;
        }
        
    }//GEN-LAST:event_btnDalActionPerformed

    private void dalto(){
        labelLogin.setIcon(new ImageIcon(getClass().getResource("/img/LoginDAO.png")));
        labelIcone.setIcon(new ImageIcon(getClass().getResource("/img/logodao.png")));
        labelFundo.setIcon(new ImageIcon(getClass().getResource("/img/fundoLogin.png")));
        labelTexto.setForeground(Color.white);
        btnEntrar.setForeground(Color.white);
        btnEntrar.setBackground(Color.black);
        btnEntrar.setIcon(new ImageIcon(getClass().getResource("/img/entrar-7.png")));
        btnSair.setForeground(Color.white);
        btnSair.setBackground(Color.black);
        btnSair.setIcon(new ImageIcon(getClass().getResource("/img/sairw.png")));
        
        lblLogin.setIcon(new ImageIcon(getClass().getResource("/img/Campo7.png")));
        lblSenha.setIcon(new ImageIcon(getClass().getResource("/img/Campo7.png")));
        txtLogin.setBackground(new Color(32,30,30));
        txtLogin.setForeground(Color.white);
        txtSenha.setBackground(new Color(32,30,30));
        txtSenha.setForeground(Color.white);
        lblNomeLogin.setForeground(Color.white);
        lblNomeSenha.setForeground(Color.white);
        
        btnDal.setIcon(new ImageIcon(getClass().getResource("/img/olhow.png")));
        btnDal.setBackground(new Color(255,246,141));
       
    }
    
    private void naoDalto(){
        labelLogin.setIcon(new ImageIcon(getClass().getResource("/img/Login.png")));
        labelIcone.setIcon(new ImageIcon(getClass().getResource("/img/logomarca_ligue180_2015(1)-2.png")));
        labelFundo.setIcon(new ImageIcon(getClass().getResource("/img/fundoLogin2.png")));
        labelTexto.setForeground(Color.black);
        btnEntrar.setForeground(Color.black);
        btnEntrar.setBackground(Color.white);
        btnEntrar.setIcon(new ImageIcon(getClass().getResource("/img/entrar-2.png")));
        btnSair.setForeground(Color.black);
        btnSair.setBackground(Color.white);
        btnSair.setIcon(new ImageIcon(getClass().getResource("/img/sairb.png")));
        
        lblLogin.setIcon(new ImageIcon(getClass().getResource("/img/Campo5.png")));
        lblSenha.setIcon(new ImageIcon(getClass().getResource("/img/Campo5.png")));
        txtLogin.setBackground(Color.white);
        txtLogin.setForeground(Color.black);
        txtSenha.setBackground(Color.white);
        txtSenha.setForeground(Color.black);
        lblNomeLogin.setForeground(Color.black);
        lblNomeSenha.setForeground(Color.black);
        
        btnDal.setIcon(new ImageIcon(getClass().getResource("/img/olho.png")));
        btnDal.setBackground(new Color(67,45,119));
    }
    
    private void btnDalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDalMouseClicked

    }//GEN-LAST:event_btnDalMouseClicked

    private void limparCampos() {
        txtLogin.setText("");
        txtSenha.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDal;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelIcone;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelTexto;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNomeLogin;
    private javax.swing.JLabel lblNomeSenha;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
